# 0. Set Up

In [2]:
# import libraries
import pandas as pd 
import pickle as pk
import numpy as np
import os
import openpyxl

In [17]:
# Reads each csv file and converts it into a 2-D data structure (Dataframe).

# Get root folder for reading data
data_fp = os.getcwd().replace('data_management/merge', 'charter_data/ccd/')

# Directory
f0 = pd.read_csv(data_fp + "ccd_201718/ccd_sch_029_1718_w_1a_083118.csv", encoding = "latin1", low_memory = False)
#f0 = pd.read_csv("ccd_2017-18/Directory1718.csv", encoding = "latin1", low_memory = False)

# Lunch Program
f1 = pd.read_csv(data_fp + "ccd_201718/ccd_sch_033_1718_l_1a_083118.csv", encoding = 'latin1', low_memory = False)
#f1 = pd.read_csv("ccd_2017-18/Lunch2017-18.csv", encoding = 'latin1', low_memory = False)

# Membership - Large file (2.4GB), may need to extra file first
f2 = pd.read_csv(data_fp + "ccd_201718/ccd_SCH_052_1718_l_1a_083118.csv", encoding = 'latin1', low_memory = False)
#f2 = pd.read_csv("ccd_2017-18/ccd_SCH_052_1718_l_1a_083118.csv", encoding = 'latin1', low_memory = False)

# Staff
f3 = pd.read_csv(data_fp + "ccd_201718/ccd_sch_059_1718_l_1a_083118.csv", encoding = 'latin1', low_memory = False)
#f3 = pd.read_csv("ccd_2017-18/staff17-18.csv", encoding = 'latin1', low_memory = False)

# School Characteristics
f4 = pd.read_csv(data_fp + "ccd_201718/ccd_sch_129_1718_w_1a_083118.csv", encoding = 'latin1', low_memory = False)
#f4 = pd.read_csv("ccd_2017-18/SchoolCharacteristics2017-18.csv", encoding = 'latin1', low_memory = False)

# School Geography
fgeo = pd.read_excel(data_fp + "ccd_201718/EDGE_GEOCODE_PUBLICSCH_1718/EDGE_GEOCODE_PUBLICSCH_1718.xlsx") #, encoding = 'latin1')

In [18]:
# pd.set_option is to display all columns when calling dataframe
pd.set_option('display.max_columns', None)
# display the number of columns and rows of each data table
display(np.shape(f0))
display(np.shape(f1))
display(np.shape(f2))
display(np.shape(f3))
display(np.shape(f4))
display(np.shape(fgeo))

(102337, 65)

(494745, 17)

(12112911, 18)

(99899, 15)

(99899, 20)

(102337, 24)

# 1. Select All Charters

In [19]:
#All the charter schools
charterSchools = f0.loc[f0['CHARTER_TEXT'] == 'Yes' , : ]
charterSchools

,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,LEA_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,NCESSCH,SCHID,MSTREET1,MSTREET2,MSTREET3,MCITY,MSTATE,MZIP,MZIP4,LSTREET1,LSTREET2,LSTREET3,LCITY,LSTATE,LZIP,LZIP4,PHONE,WEBSITE,SY_STATUS,SY_STATUS_TEXT,UPDATED_STATUS,UPDATED_STATUS_TEXT,EFFECTIVE_DATE,SCH_TYPE_TEXT,SCH_TYPE,RECON_STATUS,OUT_OF_STATE_FLAG,CHARTER_TEXT,CHARTAUTH1,CHARTAUTHN1,CHARTAUTH2,CHARTAUTHN2,NOGRADES,G_PK_OFFERED,G_KG_OFFERED,G_1_OFFERED,G_2_OFFERED,G_3_OFFERED,G_4_OFFERED,G_5_OFFERED,G_6_OFFERED,G_7_OFFERED,G_8_OFFERED,G_9_OFFERED,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED
118,2017-2018,1,ALABAMA,AL,Acceleration Day and Evening Academy,Acceleration Day and Evening Academy,1,NaN,AL-800,100197,AL-800-0010,10019702432,102432,605 Bel Air Blvd Suite 400,NaN,NaN,Mobile,AL,36606,NaN,3100 Cottage Hill Rd,NaN,NaN,Mobile,AL,36606,NaN,(251)476-0002,http://www.maef.net,1,Open,1,Open,08/17/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,09,12,High,As reported
119,2017-2018,1,ALABAMA,AL,University Charter School,University Charter School,1,NaN,AL-801,100199,AL-801-0010,10019902452,102452,108 School Street,NaN,NaN,Livingston,AL,35470,NaN,108 School Street,NaN,NaN,Livingston,AL,35470,NaN,(205)652-3438,NaN,7,Future,7,Future,04/19/2018,Regular School,1,No,No,Yes,AL001,Alabama Public Charter School Commission,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,PK,08,Elementary,As reported
1497,2017-2018,2,ALASKA,AK,Ayaprun Elitnaurvik,Lower Kuskokwim School District,1,NaN,AK-31,200001,AK-31-319010,20000100329,200329,PO Box 1468,NaN,NaN,Bethel,AK,99559,1468.0,1010 Fourth Ave,NaN,NaN,Bethel,AK,99559,NaN,(907)543-1645,http://www.lksd.org/lksd/,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200001,Lower Kuskokwim School District,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,PK,06,Elementary,As reported
1591,2017-2018,2,ALASKA,AK,Ketchikan Charter School,Ketchikan Gateway Borough School District,1,NaN,AK-25,200150,AK-25-259010,20015000306,200306,410 Schoenbar Rd,NaN,NaN,Ketchikan,AK,99901,NaN,410 Schoenbar,NaN,NaN,Ketchikan,AK,99901,NaN,(907)225-8568,http://www.kgbsd.org/ketchikancharter,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200150,Ketchikan Gateway Borough School District,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,KG,08,Elementary,As reported
1593,2017-2018,2,ALASKA,AK,Tongass School of Arts and Sciences Charter Sc...,Ketchikan Gateway Borough School District,1,NaN,AK-25,200150,AK-25-259020,20015000523,200523,410 Schoenbar Rd Ste 202,NaN,NaN,Ketchikan,AK,99901,NaN,410 Schoenbar Rd,NaN,NaN,Ketchikan,AK,99901,NaN,(907)225-5720,http://www.tongassschool.org/,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200150,Ketchikan Gateway Borough School District,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,PK,06,Elementary,As reported
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100425,2017-2018,56,WYOMING,WY,Snowy Range Academy,Albany County School District #1,1,NaN,WY-0101000,5600730,WY-0101000-0101001,560073000216,5600216,4037 Grand Avenue,Suite A,NaN,Laramie,WY,82070,NaN,4037 Grand Avenue,NaN,NaN,Laramie,WY,82070,NaN,(307)745-9930,http://www.snowyrangeacademy.org/,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,KG,08,Elementary,As reported
100428,2017-2018,56,WYOMING,WY,Laramie Montessori Charter School,Albany County School District #1,1,NaN,WY-0101000,5600730,WY-0101000-0101031,560073000542,5600542,608 S 4th St.,NaN,NaN,Laramie,WY,82070,NaN,608 S 4th St.,NaN,NaN,Laramie,WY,82070,NaN,(307)742-2554,http://www.laramiemontessori.org,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,KG,06,Elementary,As reported
100431,2017-2018,56,WYOMING,WY,Arapahoe Charter High School,Fremont County School District #38,1,NaN,WY-0738000,5600960,WY-0738000-0738055,560096000367,5600367,445 Little Wind River Bottom R,NaN,NaN,Arapahoe,WY,82510,NaN,445 Little Wind River Bottom R,NaN,NaN,Arapahoe,WY,82510,NaN,(307)856-3862,http://www.fcsd38.org,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,09,12,High,As reported
100518,2017-2018,56,WYOMING,WY,PODER Academy,Laramie County School District #1,1,NaN,WY-1101000,5601980,WY-1101000-1101040,560198000547,5600547,2201 Morrie Ave,NaN,NaN,Cheyenne,WY,82001,NaN,2201 Morrie Ave,NaN,NaN,Cheyenne,WY,82001,NaN,(307)632-2248,http://poderacademy.com,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,No,KG,05,Elementary,As reported
100521,2017-2018,56,WYOMING,WY,PODER Academy Secondary School,Laramie County School District #1,1,NaN,WY-1101000,5601980,WY-1101000-1101045,560198000574,5600574,2201 Morrie Avenue,NaN,NaN,Cheyenne,WY,82001,NaN,2201 Morrie Avenue,NaN,NaN,Cheyenne,WY,82001,NaN,(307)632-2248,http://www.poderacademy.com,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,No,No,No,06,09,Middle,As reported

In [20]:
# Check to see if there is around 7,000 charter schools
display(np.shape(charterSchools))

(7612, 65)

In [21]:
charter_id = np.array(charterSchools["NCESSCH"])
len(charter_id)

7612

# 2. Select Free and Reduced Lunch from f1 table

In [22]:
f1["LUNCH_PROGRAM"].unique()

array(['Free lunch qualified', 'Reduced-price lunch qualified', 'Missing',
       'Not Applicable', 'No Category Codes'], dtype=object)

In [23]:
lunch_labels = ['Free lunch qualified', 'Reduced-price lunch qualified']
f1_filtered = f1.loc[f1['LUNCH_PROGRAM'].isin(lunch_labels) , : ]

In [24]:
f1_wide = f1_filtered.groupby("NCESSCH").agg({"STUDENT_COUNT": ['sum']})

In [25]:
f1_wide.columns = ['Free and Reduced Lunch']

In [26]:
charter_lunch = f1_wide.loc[f1_wide.index.isin(charter_id)]
charter_lunch

              Free and Reduced Lunch
NCESSCH
10019702432                    198.0
20000100329                    115.0
20015000306                     99.0
20015000523                     91.0
20018000172                      0.0
...                              ...
560073000216                    14.0
560073000542                    37.0
560096000367                    33.0
560198000547                    82.0
560198000574                    44.0

[7195 rows x 1 columns]

# 3. Explore Membership Table - f2

In [27]:
f2["TOTAL_INDICATOR"].unique()

array(['Category Set A - By Race/Ethnicity; Sex; Grade',
       'Derived - Education Unit Total minus Adult Education Count',
       'Derived - Subtotal by Race/Ethnicity and Sex minus Adult Education Count',
       'Education Unit Total', 'Subtotal 4 - By Grade'], dtype=object)

In [28]:
# Figure out what each of these indicators mean.
f2notNan = f2.loc[pd.notnull(f2['STUDENT_COUNT']), ]

In [29]:
# specific school membership
totals_id = ["Category Set A - By Race/Ethnicity; Sex; Grade"]
f2one = f2.loc[f2["NCESSCH"] == 780003000034, ]
f2onefilter = f2one.loc[f2['TOTAL_INDICATOR'].isin(totals_id) , : ]
f2onesum = f2onefilter.agg({"STUDENT_COUNT": ['sum']})
f2onesum

     STUDENT_COUNT
sum          504.0

In [30]:
f2one.loc[f2['TOTAL_INDICATOR'] == "Education Unit Total"]

,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,NCESSCH,SCHID,GRADE,RACE_ETHNICITY,SEX,STUDENT_COUNT,TOTAL_INDICATOR,DMS_FLAG
12112906,2017-2018,78,U.S. VIRGIN ISLANDS,VI,BERTHA BOSCHULTE JUNIOR HIGH,1,NaN,VI-001,7800030,VI-001-9,780003000034,7800034,No Category Codes,No Category Codes,No Category Codes,504.0,Education Unit Total,Reported

## 4. Extract total enrollment of student of each school

In [31]:
total_member = f2.loc[f2["TOTAL_INDICATOR"] == "Education Unit Total"]
total_member

,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,NCESSCH,SCHID,GRADE,RACE_ETHNICITY,SEX,STUDENT_COUNT,TOTAL_INDICATOR,DMS_FLAG
227,2017-2018,1,ALABAMA,AL,Albertville Middle School,1,NaN,AL-101,100005,AL-101-0010,10000500870,100870,No Category Codes,No Category Codes,No Category Codes,807.0,Education Unit Total,Reported
470,2017-2018,1,ALABAMA,AL,Albertville High School,1,NaN,AL-101,100005,AL-101-0020,10000500871,100871,No Category Codes,No Category Codes,No Category Codes,1436.0,Education Unit Total,Reported
713,2017-2018,1,ALABAMA,AL,Evans Elementary School,1,NaN,AL-101,100005,AL-101-0110,10000500879,100879,No Category Codes,No Category Codes,No Category Codes,850.0,Education Unit Total,Reported
956,2017-2018,1,ALABAMA,AL,Albertville Elementary School,1,NaN,AL-101,100005,AL-101-0200,10000500889,100889,No Category Codes,No Category Codes,No Category Codes,906.0,Education Unit Total,Reported
1199,2017-2018,1,ALABAMA,AL,Big Spring Lake Kindergarten School,1,NaN,AL-101,100005,AL-101-0035,10000501616,101616,No Category Codes,No Category Codes,No Category Codes,418.0,Education Unit Total,Reported
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12112522,2017-2018,78,U.S. VIRGIN ISLANDS,VI,GLADYS A. ABRAHAM ELEMENTARY SCHOOL,1,NaN,VI-001,7800030,VI-001-21,780003000025,7800025,No Category Codes,No Category Codes,No Category Codes,279.0,Education Unit Total,Reported
12112653,2017-2018,78,U.S. VIRGIN ISLANDS,VI,ULLA F MULLER ELEMENTARY SCHOOL,1,NaN,VI-001,7800030,VI-001-17,780003000026,7800026,No Category Codes,No Category Codes,No Category Codes,334.0,Education Unit Total,Reported
12112784,2017-2018,78,U.S. VIRGIN ISLANDS,VI,YVONNE BOWSKY ELEMENTARY SCHOOL,1,NaN,VI-001,7800030,VI-001-23,780003000027,7800027,No Category Codes,No Category Codes,No Category Codes,276.0,Education Unit Total,Reported
12112840,2017-2018,78,U.S. VIRGIN ISLANDS,VI,CANCRYN JUNIOR HIGH SCHOOL,1,NaN,VI-001,7800030,VI-001-25,780003000033,7800033,No Category Codes,No Category Codes,No Category Codes,433.0,Education Unit Total,Reported
12112906,2017-2018,78,U.S. VIRGIN ISLANDS,VI,BERTHA BOSCHULTE JUNIOR HIGH,1,NaN,VI-001,7800030,VI-001-9,780003000034,7800034,No Category Codes,No Category Codes,No Category Codes,504.0,Education Unit Total,Reported

In [32]:
charter_membership = f2.loc[f2["NCESSCH"].isin(charter_id)]

In [33]:
len(charter_membership["NCESSCH"].unique())

7195

In [34]:
# calculate the total of each school
total_ch_mem = charter_membership.loc[charter_membership["TOTAL_INDICATOR"] == "Education Unit Total",['NCESSCH','STUDENT_COUNT']]
total_ch_mem

               NCESSCH  STUDENT_COUNT
27449      10019702432          245.0
343889     20000100329          166.0
362887     20015000306          186.0
363262     20015000523          179.0
372373     20018000172          385.0
...                ...            ...
11899925  560073000216          204.0
11900368  560073000542           80.0
11900796  560096000367           36.0
11910585  560198000547          174.0
11910852  560198000574           75.0

[7195 rows x 2 columns]

## 5. Calculate student total by race

In [35]:
# Total up all students by race for each school
charter_memfilter = charter_membership.loc[charter_membership['TOTAL_INDICATOR'].isin(totals_id) , : ]
charter_memgroup = charter_memfilter.groupby(["NCESSCH", 'RACE_ETHNICITY']).agg({"STUDENT_COUNT": ['sum']})
charter_memgroup

                                                       STUDENT_COUNT
                                                                 sum
NCESSCH      RACE_ETHNICITY
10019702432  American Indian or Alaska Native                    3.0
             Asian                                               2.0
             Black or African American                         177.0
             Hispanic/Latino                                     4.0
             Native Hawaiian or Other Pacific Islander           1.0
...                                                              ...
560198000574 Hispanic/Latino                                    24.0
             Native Hawaiian or Other Pacific Islander           1.0
             Not Specified                                       0.0
             Two or more races                                   2.0
             White                                              42.0

[57560 rows x 1 columns]

In [36]:
charter_memwide = charter_memgroup.unstack()

In [37]:
charter_memwide.index

Int64Index([ 10019702432,  20000100329,  20015000306,  20015000523,
             20018000172,  20018000178,  20018000459,  20018000460,
             20018000530,  20018000555,
            ...
            551629002953, 551632002752, 551650002523, 551707002781,
            551713003059, 560073000216, 560073000542, 560096000367,
            560198000547, 560198000574],
           dtype='int64', name='NCESSCH', length=7195)

In [38]:
chMemLun = charter_memwide.merge(charter_lunch, how="outer", left_index = True, right_index = True)
chMemLunTot = chMemLun.merge(total_ch_mem, how="outer", left_index = True, right_on = "NCESSCH")

/opt/conda/lib/python3.8/site-packages/pandas/core/reshape/merge.py:643: UserWarning: merging between different levels can give an unintended result (3 levels on the left,1 on the right)
  warnings.warn(msg, UserWarning)

In [39]:
ch_merged = chMemLunTot.set_index('NCESSCH')
ch_merged

,"(STUDENT_COUNT, sum, American Indian or Alaska Native)","(STUDENT_COUNT, sum, Asian)","(STUDENT_COUNT, sum, Black or African American)","(STUDENT_COUNT, sum, Hispanic/Latino)","(STUDENT_COUNT, sum, Native Hawaiian or Other Pacific Islander)","(STUDENT_COUNT, sum, Not Specified)","(STUDENT_COUNT, sum, Two or more races)","(STUDENT_COUNT, sum, White)",Free and Reduced Lunch,STUDENT_COUNT
NCESSCH,,,,,,,,,,
10019702432,3.0,2.0,177.0,4.0,1.0,0.0,8.0,50.0,198.0,245.0
20000100329,163.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,115.0,166.0
20015000306,77.0,26.0,6.0,11.0,4.0,0.0,10.0,52.0,99.0,186.0
20015000523,59.0,10.0,6.0,1.0,2.0,0.0,20.0,81.0,91.0,179.0
20018000172,10.0,11.0,5.0,28.0,1.0,0.0,55.0,275.0,0.0,385.0
...,...,...,...,...,...,...,...,...,...,...
560073000216,0.0,16.0,3.0,11.0,0.0,0.0,14.0,160.0,14.0,204.0
560073000542,3.0,0.0,0.0,15.0,0.0,0.0,4.0,58.0,37.0,80.0
560096000367,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.0,36.0
560198000547,1.0,1.0,2.0,51.0,2.0,0.0,11.0,106.0,82.0,174.0
560198000574,2.0,0.0,4.0,24.0,1.0,0.0,2.0,42.0,44.0,75.0

In [40]:
proportions = ch_merged.copy()
columns = proportions.columns
for i, row in proportions.iterrows():
    for x in range(len(columns)):
        col = columns[x]
        if col != 'STUDENT_COUNT':
            value = row[x]
            if value == 0:
                proportions.at[i, col] = 0
            else:
                proportions.at[i, col] = str((row[x] / row[len(row) - 1]) * 100)

proportions.columns = ['American Indian/Alaska Native (% total)', 'Asian (% total)', 'Black/African American (% total)', 'Hispanic/Latino (% total)', 'Hawaiian/Pacific Islander (% total)', 'Not Specified (% total)', 'Two+ races (% total)', 'White (% total)', 'Free or Reduced Lunch (% total)', 'Total Student Count']              
proportions

,American Indian/Alaska Native (% total),Asian (% total),Black/African American (% total),Hispanic/Latino (% total),Hawaiian/Pacific Islander (% total),Not Specified (% total),Two+ races (% total),White (% total),Free or Reduced Lunch (% total),Total Student Count
NCESSCH,,,,,,,,,,
10019702432,1.224490,0.816327,72.244898,1.632653,0.408163,0.0,3.265306,20.408163,80.816327,245.0
20000100329,98.192771,0.602410,0.000000,0.000000,0.000000,0.0,0.000000,1.204819,69.277108,166.0
20015000306,41.397849,13.978495,3.225806,5.913978,2.150538,0.0,5.376344,27.956989,53.225806,186.0
20015000523,32.960894,5.586592,3.351955,0.558659,1.117318,0.0,11.173184,45.251397,50.837989,179.0
20018000172,2.597403,2.857143,1.298701,7.272727,0.259740,0.0,14.285714,71.428571,0.000000,385.0
...,...,...,...,...,...,...,...,...,...,...
560073000216,0.000000,7.843137,1.470588,5.392157,0.000000,0.0,6.862745,78.431373,6.862745,204.0
560073000542,3.750000,0.000000,0.000000,18.750000,0.000000,0.0,5.000000,72.500000,46.250000,80.0
560096000367,100.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,91.666667,36.0
560198000547,0.574713,0.574713,1.149425,29.310345,1.149425,0.0,6.321839,60.919540,47.126437,174.0
560198000574,2.666667,0.000000,5.333333,32.000000,1.333333,0.0,2.666667,56.000000,58.666667,75.0

In [41]:
#Save progress
proportions.to_csv('merged2017-18.csv', header=True)

# 6. Select charter schools only for f3, f4, and fgeo

In [42]:
charter_f3 = f3.loc[f3["NCESSCH"].isin(charter_id)]

In [43]:
charter_f4 = f4.loc[f4["NCESSCH"].isin(charter_id)]

In [44]:
charter_geo = fgeo.loc[fgeo["NCESSCH"].isin(charter_id)]

In [45]:
len(charter_geo)

7612

# 7. Merge all Tables

In [46]:
#Merge All tables
mergef02017_18 = charterSchools.merge(proportions, how="outer", left_on = "NCESSCH", right_index = True)

In [47]:
mergef32017_18 = mergef02017_18.merge(charter_f3, how="outer", left_on = "NCESSCH", right_on = "NCESSCH")

In [48]:
mergef42017_18 = mergef32017_18.merge(charter_f4, how="outer", left_on = "NCESSCH", right_on = "NCESSCH")

In [49]:
mergeAll2017_18 = mergef42017_18.merge(charter_geo, how="outer", left_on = "NCESSCH", right_on = "NCESSCH")

In [50]:
mergeAll2017_18

,SCHOOL_YEAR_x,FIPST_x,STATENAME_x,ST_x,SCH_NAME_x,LEA_NAME,STATE_AGENCY_NO_x,UNION_x,ST_LEAID_x,LEAID_x,ST_SCHID_x,NCESSCH,SCHID_x,MSTREET1,MSTREET2,MSTREET3,MCITY,MSTATE,MZIP,MZIP4,LSTREET1,LSTREET2,LSTREET3,LCITY,LSTATE,LZIP,LZIP4,PHONE,WEBSITE,SY_STATUS,SY_STATUS_TEXT,UPDATED_STATUS,UPDATED_STATUS_TEXT,EFFECTIVE_DATE,SCH_TYPE_TEXT,SCH_TYPE,RECON_STATUS,OUT_OF_STATE_FLAG,CHARTER_TEXT,CHARTAUTH1,CHARTAUTHN1,CHARTAUTH2,CHARTAUTHN2,NOGRADES,G_PK_OFFERED,G_KG_OFFERED,G_1_OFFERED,G_2_OFFERED,G_3_OFFERED,G_4_OFFERED,G_5_OFFERED,G_6_OFFERED,G_7_OFFERED,G_8_OFFERED,G_9_OFFERED,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED,American Indian/Alaska Native (% total),Asian (% total),Black/African American (% total),Hispanic/Latino (% total),Hawaiian/Pacific Islander (% total),Not Specified (% total),Two+ races (% total),White (% total),Free or Reduced Lunch (% total),Total Student Count,SCHOOL_YEAR_y,FIPST_y,STATENAME_y,ST_y,SCH_NAME_y,STATE_AGENCY_NO_y,UNION_y,ST_LEAID_y,LEAID_y,ST_SCHID_y,SCHID_y,TEACHERS,TOTAL_INDICATOR,DMS_FLAG,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,SCHID,SHARED_TIME,TITLEI_STATUS,TITLEI_STATUS_TEXT,MAGNET_TEXT,NSLP_STATUS,NSLP_STATUS_TEXT,VIRTUAL,VIRTUAL_TEXT,NAME,OPSTFIPS,STREET,CITY,STATE,ZIP,STFIP,CNTY,NMCNTY,LOCALE,LAT,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,NECTA,NMNECTA,CD,SLDL,SLDU,SCHOOLYEAR
0,2017-2018,1,ALABAMA,AL,Acceleration Day and Evening Academy,Acceleration Day and Evening Academy,1,NaN,AL-800,100197,AL-800-0010,10019702432,102432,605 Bel Air Blvd Suite 400,NaN,NaN,Mobile,AL,36606,NaN,3100 Cottage Hill Rd,NaN,NaN,Mobile,AL,36606,NaN,(251)476-0002,http://www.maef.net,1,Open,1,Open,08/17/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,09,12,High,As reported,1.224490,0.816327,72.244898,1.632653,0.408163,0.0,3.265306,20.408163,80.816327,245.0,2017-2018,1.0,ALABAMA,AL,Acceleration Day and Evening Academy,1.0,NaN,AL-800,100197.0,AL-800-0010,102432.0,7.00,Education Unit Total,Reported,2017-2018,1.0,ALABAMA,AL,Acceleration Day and Evening Academy,1.0,NaN,AL-800,100197.0,AL-800-0010,102432.0,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Acceleration Day and Evening Academy,1,3100 Cottage Hill Rd,Mobile,AL,36606,1,1097,Mobile County,12,30.668018,-88.119730,33660,"Mobile, AL",1,380,"Mobile-Daphne-Fairhope, AL",N,N,101,01103,01033,2017-2018
1,2017-2018,1,ALABAMA,AL,University Charter School,University Charter School,1,NaN,AL-801,100199,AL-801-0010,10019902452,102452,108 School Street,NaN,NaN,Livingston,AL,35470,NaN,108 School Street,NaN,NaN,Livingston,AL,35470,NaN,(205)652-3438,NaN,7,Future,7,Future,04/19/2018,Regular School,1,No,No,Yes,AL001,Alabama Public Charter School Commission,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,PK,08,Elementary,As reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,University Charter School,1,108 School Street,Livingston,AL,35470,1,1119,Sumter County,43,32.586288,-88.189067,N,N,0,N,N,N,N,107,01072,01024,2017-2018
2,2017-2018,2,ALASKA,AK,Ayaprun Elitnaurvik,Lower Kuskokwim School District,1,NaN,AK-31,200001,AK-31-319010,20000100329,200329,PO Box 1468,NaN,NaN,Bethel,AK,99559,1468.0,1010 Fourth Ave,NaN,NaN,Bethel,AK,99559,NaN,(907)543-1645,http://www.lksd.org/lksd/,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200001,Lower Kuskokwim School District,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,PK,06,Elementary,As reported,98.192771,0.602410,0.000000,0.000000,0.000000,0.0,0.000000,1.204819,69.277108,166.0,2017-2018,2.0,ALASKA,AK,Ayaprun Elitnaurvik,1.0,NaN,AK-31,200001.0,AK-31-319010,200329.0,9.13,Education Unit Total,Reported,2017-2018,2.0,ALASKA,AK,Ayaprun Elitnaurvik,1.0,NaN,AK-31,200001.0,AK-31-319010,200329.0,No,SWELIGTGPROG,Title I schoolwide eligible-Title I targeted a...,No,NSLPCEO,Yes under Community Eligibility Option (CEO),NOTVIRTUAL,Not Virtual,Ayaprun Elitnaurvik,2,1010 Fourth Ave,Bethel,AK,99559,2,2050,Bethel Census Area,33,60.796131,-161.765194,N,N,0,N,N,N,N,200,02038,0200S,2017-2018
3,2017-2018,2,ALASKA,AK,Ketchikan Charter School,Ketchikan Gateway Borough School District,1,NaN,AK-25,200150,AK-25-259010,20015000306,200306,410 Schoenbar Rd,NaN,NaN,Ketchikan,AK,99901,NaN,410 Schoenbar,NaN,NaN,Ketchikan,AK,99901,NaN,(907)225-8568,http://www.kgbsd.org/ketchikancharter,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200150,Ketchikan Gateway Borough School District,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,KG,08,Elementary,As reported,41.397849,13.978495,3.225806,5.913978,2.150538,0.0,5.376344,27.956989,53.225806,186.0,2017-2018,2.0,ALASKA,AK,Ketchikan Charter School,1.0,NaN,AK-25,200150.0,AK-25-259010,200306.0,11.80,Education Unit Total,Reported,2017-2018,2.0,ALASKA,AK,Ketchikan Charter School,1.0,NaN,AK-25,200150.0,AK-25-259010,200306.0,No,SWELIGTGPROG,Title I schoolwide eligible-Title I targeted a...,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Ketchikan Charter School,2,410 Schoenbar,Ketchikan,AK,99901,2,2130,Ketchikan Gateway Borough,33,55.347575,-131.640006,28540,"Ketchikan, AK",2,N,N,N,N,200,02036,0200R,2017-2018
4,2017-2018,2,ALASKA,AK,Tongass School of Arts and Sciences Charter Sc...,Ketchikan Gateway Borough School District,1,NaN,AK-25,200150,AK-25-259020,20015000523,200523,410 Schoenbar Rd Ste 202,NaN,NaN,Ketchikan,AK,99901,NaN,410 Schoenbar Rd,NaN,NaN,Ketchikan,AK,99901,NaN,(907)225-5720,http://www.tongassschool.org/,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200150,Ketchikan Gateway Borough School District,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,PK,06,Elementary,As reported,32.960894,5.586592,3.351955,0.558659,1.117318,0.0,11.173184,45.251397,50.837989,179.0,2017-2018,2.0,ALASKA,AK,Tongass School of Arts and Sciences Charter Sc...,1.0,NaN,AK-25,200150.0,AK-25-259020,200523.0,11.10,Education Unit Total,Reported,2017-2018,2.0,ALASKA,AK,Tongass School of Arts and Sciences Charter Sc...,1.0,NaN,AK-25,200150.0,AK-25-259020,200523.0,No,SWELIGTGPROG,Title I schoolwide eligible-Title I targeted a...,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Tongass School of Arts and Sciences Charter Sc...,2,410 Schoenbar Rd,Ketchikan,AK,99901,2,2130,Ketchikan Gateway Borough,33,55.347575,-131.640006,28540,"Ketchikan, AK",2,N,N,N,N,200,02036,0200R,2017-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7607,2017-2018,56,WYOMING,WY,Snowy Range Academy,Albany County School District #1,1,NaN,WY-0101000,5600730,WY-0101000-0101001,560073000216,5600216,4037 Grand Avenue,Suite A,NaN,Laramie,WY,82070,NaN,4037 Grand Avenue,NaN,NaN,Laramie,WY,82070,NaN,(307)745-9930,http://www.snowyrangeacademy.org/,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,KG,08,Elementary,As reported,0.000000,7.843137,1.470588,5.392157,0.000000,0.0,6.862745,78.431373,6.862745,204.0,2017-2018,56.0,WYOMING,WY,Snowy Range Academy,1.0,NaN,WY-0101000,5600730.0,WY-0101000-0101001,5600216.0,20.50,Education Unit Total,Reported,2017-2018,56.0,WYOMING,WY,Snowy Range Academy,1.0,NaN,WY-0101000,5600730.0,WY-0101000-0101001,5600216.0,No,NOTTITLE1ELIG,Not a Title I school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Snowy Range Academy,56,4037 Grand Avenue,Laramie,WY,82070,56,56001,Albany County,41,41.307523,-105.544698,29660,"Laramie, WY",2,N,N,N,N,5600,56014,56010,2017-2018
7608,2017-2018,56,WYOMING,WY,Laramie Montessori Charter School,Albany County School District #1,1,NaN,WY-0101000,5600730,WY-0101000-0101031,560073000542,5600542,608 S 4th St.,NaN,NaN,Laramie,WY,82070,NaN,608 S 4th St.,NaN,NaN,Laramie,WY,82070,NaN,(307)742-2554,http://www.laramiemontessori.org,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,KG,06,Elementary,As reported,3.750000,0.000000,0.000000,18.750000,0.000000,0.0,5.000000,72.500000,46.250000,80.0,2017-2018,56.0,WYOMING,WY,Laramie Montessori Charter School,1.0,NaN,WY-0101000,5600730.0,WY-0101000-0101031,5600542.0,7.41,Education Unit Total,Reported,2017-2018,56.0,WYOMING,WY,Laramie Montessori Charter School,1.0,NaN,WY-0101000,5600730.0,WY-0101000-0101031,5600542.0,No,TGELGBTGPROG,Title I targeted assistance school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Laramie Montessori Charter School,56,608 S 4th St.,Laramie,WY,82070,56,56001,Albany County,33,41.307729,-105.593028,29660,"Laramie, WY",2,N,N,N,N,5600,56045,56009,2017-2018
7609,2017-2018,56,WYOMING,WY,Arapahoe Charter High School,Fremont County School District #38,1,NaN,WY-0738000,5600960,WY-0738000-0738055,560096000367,5600367,445 Little Wind River Bottom R,NaN,NaN,Arapahoe,WY,82510,NaN,445 Little Wind River Bottom R,NaN,NaN,Arapahoe,WY,82510,NaN,(307)856-3862,http://www.fcsd38.org,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,09,12,High,As reported,100.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,91.666667,36.0,2017-2018,56.0,WYOMING,WY,Arapahoe Charter High School,1.0,NaN,WY-0738000,5600960.0,WY-0738000-0738055,5600367.0,3.14,Education Unit Total,Reported,2017-2018,56.0,WYOMING,WY,Arapahoe Charter High School,1.0,NaN,WY-0738000,5600960.0,WY-0738000-0738055,5600367.0,No,SWELIGSWPROG,Title I schoolwide school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Arapahoe Charter High School,56,445 Little Wind River Bottom R,Arapahoe,WY,82510,56,56013,Fremont County,42,42.963943,-108.490183,40180,"Riverton, WY",2,N,N,N,N,5600,56033,56025,2017-2018
7610,2017-2018,56,WYOMING,WY,PODER Academy,Laramie County School District #1,1,NaN,WY-1101000,5601980,WY-1101000-1101040,560198000547,5600547,2201 Morrie Ave,NaN,NaN,Cheyenne,WY,82001,NaN,2201 Morrie Ave,NaN,NaN,Cheyenne,WY,82001,NaN,(307)632-2248,http://poderacademy.com,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,No,KG,05,Elementary,As reported,0.574713,0.574713,1.149425,29.310345,1.149425,0.0,6.321839,60.919540,47.126437,174.0,2017-2018,56.0,WYOMING,WY,PODER Academy,1.0,NaN,WY-1101000,5601980.0,WY-1101000-1101040,5600547.0,8.25,Education Unit Total,Reported,2017-2018,56.0,WYOMING,WY,PODER Academy,1.0,NaN,WY-1101000,5601980.0,WY-1101000-1101040,5600547.0,No,SWELIGSWPROG,Title I schoolwide school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,PODER Academy,56,2201 Morrie Ave,Cheyenne,WY,82001,56,56021,Laramie County,13,41.142854,-104.807608,16940,"Cheyenne, WY",1,N,N,N,N,5600,56011,56007,2017-2018
7611,2017-2018,56,WYOMING,WY,PODER Academy Secondary School,Laramie County School District #1,1,NaN,WY-1101000,5601980,WY-1101000-1101045,560198000574,5600574,2201 Morrie Avenue,NaN,NaN,Cheyenne,WY,82001,NaN,2201 Morrie Avenue,NaN,NaN,Cheyenne,WY,82001,NaN,(307)632-2248,http://www.poderacademy.com,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,No,No,No,06,09,Middle,As reported,2.666667,0.000000,5.333333,32.000000,1.333333,0.0,2.666667,56.000000,58.666667,75.0,2017-2018,56.0,WYOMING,WY,PODER Academy Secondary School,1.0,NaN,WY-1101000,5601980.0,WY-1101000-1101045,5600574.0,2.70,Education Unit Total,Reported,2017-2018,56.0,WYOMING,WY,PODER Academy Secondary School,1.0,NaN,WY-1101000,5601980.0,WY-1101000-1101045,5600574.0,No,TGELGBTGPROG,Title I targeted assistance school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,PODER Academy Secondary School,56,2201 Morrie Avenue,Cheyenne,WY,82001,56,56021,Laramie County,13,41.142854,-104.807608,16940,"Cheyenne, WY",1,N,N,N,N,5600,56011,56007,2017-2018

In [51]:
#Save progress
mergeAll2017_18.to_csv('All_Charters2017_18.csv', header=True)

# 8. Perform Check on full merged table

In [53]:
#Perform Check
mergeAll2017_18.loc[mergeAll2017_18["SCH_NAME_x"] == "Aquarian Charter School", ]
#Passes Check

,SCHOOL_YEAR_x,FIPST_x,STATENAME_x,ST_x,SCH_NAME_x,LEA_NAME,STATE_AGENCY_NO_x,UNION_x,ST_LEAID_x,LEAID_x,ST_SCHID_x,NCESSCH,SCHID_x,MSTREET1,MSTREET2,MSTREET3,MCITY,MSTATE,MZIP,MZIP4,LSTREET1,LSTREET2,LSTREET3,LCITY,LSTATE,LZIP,LZIP4,PHONE,WEBSITE,SY_STATUS,SY_STATUS_TEXT,UPDATED_STATUS,UPDATED_STATUS_TEXT,EFFECTIVE_DATE,SCH_TYPE_TEXT,SCH_TYPE,RECON_STATUS,OUT_OF_STATE_FLAG,CHARTER_TEXT,CHARTAUTH1,CHARTAUTHN1,CHARTAUTH2,CHARTAUTHN2,NOGRADES,G_PK_OFFERED,G_KG_OFFERED,G_1_OFFERED,G_2_OFFERED,G_3_OFFERED,G_4_OFFERED,G_5_OFFERED,G_6_OFFERED,G_7_OFFERED,G_8_OFFERED,G_9_OFFERED,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED,American Indian/Alaska Native (% total),Asian (% total),Black/African American (% total),Hispanic/Latino (% total),Hawaiian/Pacific Islander (% total),Not Specified (% total),Two+ races (% total),White (% total),Free or Reduced Lunch (% total),Total Student Count,SCHOOL_YEAR_y,FIPST_y,STATENAME_y,ST_y,SCH_NAME_y,STATE_AGENCY_NO_y,UNION_y,ST_LEAID_y,LEAID_y,ST_SCHID_y,SCHID_y,TEACHERS,TOTAL_INDICATOR,DMS_FLAG,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,SCHID,SHARED_TIME,TITLEI_STATUS,TITLEI_STATUS_TEXT,MAGNET_TEXT,NSLP_STATUS,NSLP_STATUS_TEXT,VIRTUAL,VIRTUAL_TEXT,NAME,OPSTFIPS,STREET,CITY,STATE,ZIP,STFIP,CNTY,NMCNTY,LOCALE,LAT,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,NECTA,NMNECTA,CD,SLDL,SLDU,SCHOOLYEAR
5,2017-2018,2,ALASKA,AK,Aquarian Charter School,Anchorage School District,1,NaN,AK-05,200180,AK-05-059010,20018000172,200172,1705 W 32nd Ave,NaN,NaN,Anchorage,AK,99517,2002.0,1705 W 32nd Ave,NaN,NaN,Anchorage,AK,99517,NaN,(907)742-4900,http://aquarian.asdk12.org/,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200180,Anchorage School District,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,KG,06,Elementary,As reported,2.597403,2.857143,1.298701,7.272727,0.25974,0.0,14.285714,71.428571,0.0,385.0,2017-2018,2.0,ALASKA,AK,Aquarian Charter School,1.0,NaN,AK-05,200180.0,AK-05-059010,200172.0,22.13,Education Unit Total,Reported,2017-2018,2.0,ALASKA,AK,Aquarian Charter School,1.0,NaN,AK-05,200180.0,AK-05-059010,200172.0,No,NOTTITLE1ELIG,Not a Title I school,No,NSLPNO,No,NOTVIRTUAL,Not Virtual,Aquarian Charter School,2,1705 W 32nd Ave,Anchorage,AK,99517,2,2020,Anchorage Municipality,11,61.192407,-149.916872,11260,"Anchorage, AK",1,N,N,N,N,200,02018,0200I,2017-2018

# 9. Find new Charters

In [56]:
#Find New Charters 
charter_recorded = pd.read_csv(data_fp + "checking_charter_URLS_2016_full_list.csv", low_memory = False)
charter1718 = mergeAll2017_18.copy()

In [57]:
ncessch_recorded = charter_recorded["NCESSCH"]
ncessch_1718 = charter1718["NCESSCH"]

In [58]:
# Create function to filter the new NCESSCH values
def filarray(series, check_to):
    indexes = []
    for i in range(0, len(series)):
        if series[i] not in check_to:
            indexes.append(i)
    return indexes

In [59]:
# Turn series into np arrays
ncessch_1718 = np.array(ncessch_1718)
ncessch_recorded = np.array(ncessch_recorded)

In [60]:
# filter the ncessch from the 2016-17 data to the spreadsheet and select the new values
new_indexes = filarray(ncessch_1718, ncessch_recorded)

In [61]:
# Display new schools
pd.set_option('display.max_columns', None)
new_charters = charter1718.iloc[new_indexes, :]
new_charters

,SCHOOL_YEAR_x,FIPST_x,STATENAME_x,ST_x,SCH_NAME_x,LEA_NAME,STATE_AGENCY_NO_x,UNION_x,ST_LEAID_x,LEAID_x,ST_SCHID_x,NCESSCH,SCHID_x,MSTREET1,MSTREET2,MSTREET3,MCITY,MSTATE,MZIP,MZIP4,LSTREET1,LSTREET2,LSTREET3,LCITY,LSTATE,LZIP,LZIP4,PHONE,WEBSITE,SY_STATUS,SY_STATUS_TEXT,UPDATED_STATUS,UPDATED_STATUS_TEXT,EFFECTIVE_DATE,SCH_TYPE_TEXT,SCH_TYPE,RECON_STATUS,OUT_OF_STATE_FLAG,CHARTER_TEXT,CHARTAUTH1,CHARTAUTHN1,CHARTAUTH2,CHARTAUTHN2,NOGRADES,G_PK_OFFERED,G_KG_OFFERED,G_1_OFFERED,G_2_OFFERED,G_3_OFFERED,G_4_OFFERED,G_5_OFFERED,G_6_OFFERED,G_7_OFFERED,G_8_OFFERED,G_9_OFFERED,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED,American Indian/Alaska Native (% total),Asian (% total),Black/African American (% total),Hispanic/Latino (% total),Hawaiian/Pacific Islander (% total),Not Specified (% total),Two+ races (% total),White (% total),Free or Reduced Lunch (% total),Total Student Count,SCHOOL_YEAR_y,FIPST_y,STATENAME_y,ST_y,SCH_NAME_y,STATE_AGENCY_NO_y,UNION_y,ST_LEAID_y,LEAID_y,ST_SCHID_y,SCHID_y,TEACHERS,TOTAL_INDICATOR,DMS_FLAG,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,SCHID,SHARED_TIME,TITLEI_STATUS,TITLEI_STATUS_TEXT,MAGNET_TEXT,NSLP_STATUS,NSLP_STATUS_TEXT,VIRTUAL,VIRTUAL_TEXT,NAME,OPSTFIPS,STREET,CITY,STATE,ZIP,STFIP,CNTY,NMCNTY,LOCALE,LAT,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,NECTA,NMNECTA,CD,SLDL,SLDU,SCHOOLYEAR
1,2017-2018,1,ALABAMA,AL,University Charter School,University Charter School,1,NaN,AL-801,100199,AL-801-0010,10019902452,102452,108 School Street,NaN,NaN,Livingston,AL,35470,NaN,108 School Street,NaN,NaN,Livingston,AL,35470,NaN,(205)652-3438,NaN,7,Future,7,Future,04/19/2018,Regular School,1,No,No,Yes,AL001,Alabama Public Charter School Commission,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,PK,08,Elementary,As reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,University Charter School,1,108 School Street,Livingston,AL,35470,1,1119,Sumter County,43,32.586288,-88.189067,N,N,0,N,N,N,N,107,01072,01024,2017-2018
30,2017-2018,2,ALASKA,AK,Boreal Sun Charter School,Fairbanks North Star Borough School District,1,NaN,AK-16,200600,AK-16-169060,20060000761,200761,2404 S Barnette St,NaN,NaN,Fairbanks,AK,99701,NaN,2404 S Barnette St,NaN,NaN,Fairbanks,AK,99701,NaN,(907)456-5444,http://www.k12northstar.org/borealsun,3,New,3,New,02/20/2018,Regular School,1,No,No,Yes,0200600,Fairbanks North Star Borough School District,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,KG,07,Elementary,As reported,2.793296,1.675978,2.234637,4.469274,0.000000,0.0,9.497207,79.329609,0.0,179.0,2017-2018,2.0,ALASKA,AK,Boreal Sun Charter School,1.0,NaN,AK-16,200600.0,AK-16-169060,200761.0,10.38,Education Unit Total,Reported,2017-2018,2.0,ALASKA,AK,Boreal Sun Charter School,1.0,NaN,AK-16,200600.0,AK-16-169060,200761.0,No,NOTTITLE1ELIG,Not a Title I school,No,NSLPNO,No,NOTVIRTUAL,Not Virtual,Boreal Sun Charter School,2,2404 S Barnette St,Fairbanks,AK,99701,2,2090,Fairbanks North Star Borough,13,64.824800,-147.731661,21820,"Fairbanks, AK",1,N,N,N,N,200,02001,0200A,2017-2018
103,2017-2018,4,ARIZONA,AZ,Ombudsman - Charter East,Ombudsman Educational Services Ltd. a subsidia...,1,NaN,AZ-4323,400103,AZ-4323-5493,40010301583,401583,3943 E. Thomas Road,NaN,NaN,Phoenix,AZ,85018,NaN,3943 E. Thomas Road,NaN,NaN,Phoenix,AZ,85018,NaN,(602)275-4815,http://az.ombudsman.com/charter-east/,1,Open,1,Open,01/26/2018,Regular School,1,No,No,Yes,10500,Arizona State Board for Charter Schools,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,09,12,High,As reported,8.602151,0.000000,7.526882,72.043011,0.000000,0.0,1.075269,10.752688,0.0,93.0,2017-2018,4.0,ARIZONA,AZ,Ombudsman - Charter East,1.0,NaN,AZ-4323,400103.0,AZ-4323-5493,401583.0,NaN,Education Unit Total,Missing,2017-2018,4.0,ARIZONA,AZ,Ombudsman - Charter East,1.0,NaN,AZ-4323,400103.0,AZ-4323-5493,401583.0,No,NOTTITLE1ELIG,Not a Title I school,Missing,NSLPNO,No,NOTVIRTUAL,Not Virtual,Ombudsman - Charter East,4,3943 E. Thomas Road,Phoenix,AZ,85018,4,4013,Maricopa County,11,33.479939,-111.996269,38060,"Phoenix-Mesa-Scottsdale, AZ",1,N,N,N,N,407,04024,04024,2017-2018
108,2017-2018,4,ARIZONA,AZ,Ombudsman - Charter East II,Ombudsman Educational Services Ltd. a subsidia...,1,NaN,AZ-4323,400103,AZ-4323-89440,40010302855,402855,4041 E. Thomas Road,NaN,NaN,Phoenix,AZ,85018,NaN,4041 E. Thomas Road,NaN,NaN,Phoenix,AZ,85018,NaN,(602)667-7759,http://az.ombudsman.com/charter-east-2/,1,Open,1,Open,01/26/2018,Regular School,1,No,No,Yes,10500,Arizona State Board for Charter Schools,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,09,12,High,As reported,5.161290,0.000000,8.387097,78.709677,0.000000,0.0,0.000000,7.741935,0.0,155.0,2017-2018,4.0,ARIZONA,AZ,Ombudsman - Charter East II,1.0,NaN,AZ-4323,400103.0,AZ-4323-89440,402855.0,NaN,Education Unit Total,Missing,2017-2018,4.0,ARIZONA,AZ,Ombudsman - Charter East II,1.0,NaN,AZ-4323,400103.0,AZ-4323-89440,402855.0,No,NOTTITLE1ELIG,Not a Title I school,Missing,NSLPNO,No,NOTVIRTUAL,Not Virtual,Ombudsman - Charter East II,4,4041 E. Thomas Road,Phoenix,AZ,85018,4,4013,Maricopa County,11,33.479926,-111.993746,38060,"Phoenix-Mesa-Scottsdale, AZ",1,N,N,N,N,407,04024,04024,2017-2018
109,2017-2018,4,ARIZONA,AZ,Ombudsman - Charter Valencia,Ombudsman Educational Services Ltd. a subsidia...,1,NaN,AZ-4323,400103,AZ-4323-89827,40010302950,402950,1660 W. Valencia Road,NaN,NaN,Tucson,AZ,85746,NaN,1660 W. Valencia Road,NaN,NaN,Tucson,AZ,85746,NaN,(520)573-5858,http://az.ombudsman.com/charter-valencia/,1,Open,1,Open,01/26/2018,Regular School,1,No,No,Yes,10500,Arizona State Board for Charter Schools,NaN,NaN,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,06,12,High,As reported,20.554273,0.461894,2.309469,72.055427,0.230947,0.0,0.000000,4.387991,0.0,433.0,2017-2018,4.0,ARIZONA,AZ,Ombudsman - Charter Valencia,1.0,NaN,AZ-4323,400103.0,AZ-4323-89827,402950.0,NaN,Education Unit Total,Missing,2017-2018,4.0,ARIZONA,AZ,Ombudsman - Charter Valencia,1.0,NaN,AZ-4323,400103.0,AZ-4323-89827,402950.0,No,NOTTITLE1ELIG,Not a Title I school,Missing,NSLPNO,No,NOTVIRTUAL,Not Virtual,Ombudsman - Charter Valencia,4,1660 W. Valencia Road,Tucson,AZ,85746,4,4019,Pima County,11,32.136471,-111.002207,46060,"Tucson, AZ",1,536,"Tucson-Nogales, AZ",N,N,403,04004,04004,2017-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7530,2017-2018,55,WISCONSIN,WI,WISE Academy,Nekoosa School District,1,NaN,WI-3906,5510380,WI-3906-0800,551038003089,5503089,540 Birch St,NaN,NaN,Nekoosa,WI,54457,1318.0,540 Birch St,NaN,NaN,Nekoosa,WI,54457,1318.0,(715)886-8000,http://nekoosasd.net,7,Future,7,Future,08/01/2018,Regular School,1,No,No,Yes,3906,Nekoosa School District,NaN,NaN,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,M,M,Not Reported,As reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WISE Academy,55,540 Birch St,Nekoosa,WI,54457,55,55141,Wood County,41,44.309343,-89.916676,49220,"Wisconsin Rapids-Marshfield, WI",2,554,"Wausau-Stevens Point-Wisconsin Rapids, WI",N,N,5503,55070,55024,2017-2018
7535,2017-2018,55,WISCONSIN,WI,Norris Academy Virtual School,Norris School District,1,NaN,WI-3976,5510710,WI-3976-0800,551071003072,5503072,W247S10395 Centr Dr,NaN,NaN,Mukwonago,WI,53149,9145.0,W247S10395 Centr Dr,NaN,NaN,Mukwonago,WI,53149,9145.0,(262)662-5911,http://www.norrisacademywi.org,3,New,3,New,01/25/2018,Alternative School,4,No,No,Yes,3976,Norris School District,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,KG,12,Other,As reported,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,2017-2018,55.0,WISCONSIN,WI,Norris Academy Virtual School,1.0,NaN,WI-3976,5510710.0,WI-3976-0800,5503072.0,0.50,Education Unit Total,Reported,2017-2018,55.0,WISCONSIN,WI,Norris Academy Virtual School,1.0,NaN,WI-3976,5510710.0,WI-3976-0800,5503072.0,No,NOTTITLE1ELIG,Not a Title I school,No,NSLPNO,No,FACEVIRTUAL,Virtual with face to face options,Norris Academy Virtual School,55,W247S10395 Centr Dr,Mukwonago,WI,53149,55,55133,Waukesha County,41,42.854872,-88.243489,33340,"Milwaukee-Waukesha-West Allis, WI",1,376,"Milwaukee-Racine-Waukesha, WI",N,N,5501,55083,55028,2017-2018
7568,2017-2018,55,WISCONSIN,WI,Eagles' Wings Virtual Charter School,Solon Springs School District,1,NaN,WI-5397,5513980,WI-5397-0850,551398003092,5503092,8993 E Baldwin Ave,NaN,NaN,Solon Springs,WI,54873,8144.0,8993 E Baldwin Ave,NaN,NaN,Solon Springs,WI,54873,8144.0,(715)378-2263,http://www.solonk12.net,7,Future,7,Future,08/01/2018,Regular School,1,No,No,Yes,5397,Solon Springs School District,NaN,NaN,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,M,M,Not Reported,As reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eagles' Wings Virtual Charter School,55,8993 E Baldwin Ave,Solon Springs,WI,54873,55,55031,Douglas County,42,46.346085,-91.831277,20260,"Duluth, MN-WI",1,N,N,N,N,5507,55073,55025,2017-2018
7594,2017-2018,55,WISCONSIN,WI,Chain Exploration Center,Waupaca School District,1,NaN,WI-6195,5515840,WI-6195-0180,551584003091,5503091,N3160 Silver Lake Dr,NaN,NaN,Waupaca,WI,54981,9596.0,N3160 Silver Lake Dr,NaN,NaN,Waupaca,WI,54981,9596.0,(715)258-4151,http://www.waupaca.k12.wi.us/schools/charter,7,Future,7,Future,08/01/2018,Regular School,1,No,No,Yes,6195,Waupaca School District,NaN,NaN,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,M,M,Not Reported,As reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chain Exploration Center,55,N3160 Silver Lake Dr,Waupaca,WI,54981,55,55135,Waupaca County,41,44.354434,-89.168792,N,N,0,N,N,N,N,5508,55040,55014,2017-2018
7606,2017-2018,55,WISCONSIN,WI,Wonewoc-Center Virtual Academy,Wonewoc-Union Center School District,1,NaN,WI-6713,5517130,WI-6713-0850,551713003059,5503059,101 School Rd,NaN,NaN,Wonewoc,WI,53968,NaN,101 School Rd,NaN,NaN,Wonewoc,WI,53968,NaN,(608)464-3165,http://www.wc.k12.wi.us/virtualacademy.cfm,3,New,3,New,01/25/2018,Regular School,1,No,No,Yes,6713,Wonewoc-Union Center School District,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,KG,12,Other,As reported,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,100.000000,0.000000,0.0,1.0,2017-2018,55.0,WISCONSIN,WI,Wonewoc-Center Virtual Academy,1.0,NaN,WI-6713,5517130.0,WI-6713-0850,5503059.0,1.10,Education Unit Total,Reported,2017-2018,55.0,WISCONSIN,WI,Wonewoc-Center Virtual Academy,1.0,NaN,WI-6713,5517130.0,WI-6713-0850,5503059.0,No,TGELGBNOPROG,Title I targeted assistance eligible school-No...,No,NSLPNO,No,FULLVIRTUAL,Full Virtual,Wonewoc-Center Virtual Academy,55,101 School Rd,Wonewoc,WI,53968,55,55057,Juneau County,43,43.662531,-90.222950,N,N,0,N,N,N,N,5503,55050,55017,2017-2018

In [62]:
len(new_charters['NCESSCH'])

574

In [63]:
#Save new charters
new_charters.to_csv('new_charters17-18_v2.csv', header=True)

In [64]:
new_charters["SCH_NAME_x"]

1                  University Charter School
30                 Boreal Sun Charter School
103                 Ombudsman - Charter East
108              Ombudsman - Charter East II
109             Ombudsman - Charter Valencia
                        ...
7530                            WISE Academy
7535           Norris Academy Virtual School
7568    Eagles' Wings Virtual Charter School
7594                Chain Exploration Center
7606          Wonewoc-Center Virtual Academy
Name: SCH_NAME_x, Length: 574, dtype: object

# 10. Drop Repetitive Columns and clean full merged table

In [65]:
# Drop Repetitive Columns
charter_drop = charter1718.drop(['SCHOOL_YEAR_y', 'FIPST_y', 'STATENAME_y', 'ST_y', 'SCH_NAME_y', 'STATE_AGENCY_NO_y', 'UNION_y', 'ST_LEAID_y','LEAID_y', 'ST_SCHID_y','SCHID_y'
                 ,'SCHOOL_YEAR', 'FIPST', 'STATENAME', 'ST', 'SCH_NAME', 'STATE_AGENCY_NO', 'UNION', 'ST_LEAID','LEAID', 'ST_SCHID','SCHID', ], axis=1)

In [66]:
cleaned_charter = charter_drop.rename(columns={'SCHOOL_YEAR_x':'SCHOOL_YEAR',
                                               'FIPST_x' : 'FIPST',
                                               'STATENAME_x' : 'STATENAME', 
                                               'ST_x' : 'ST',
                                               'SCH_NAME_x' : 'SCH_NAME',
                                               'STATE_AGENCY_NO_x' : 'STATE_AGENCY_NO',
                                               'UNION_x' : 'UNION',
                                               'ST_LEAID_x' : 'ST_LEAID',
                                               'LEAID_x': 'LEAID',
                                               'ST_SCHID_x' : 'ST_SCHID' ,
                                               'SCHID_x' : 'SCHID'})

In [67]:
cleaned_charter

,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,LEA_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,NCESSCH,SCHID,MSTREET1,MSTREET2,MSTREET3,MCITY,MSTATE,MZIP,MZIP4,LSTREET1,LSTREET2,LSTREET3,LCITY,LSTATE,LZIP,LZIP4,PHONE,WEBSITE,SY_STATUS,SY_STATUS_TEXT,UPDATED_STATUS,UPDATED_STATUS_TEXT,EFFECTIVE_DATE,SCH_TYPE_TEXT,SCH_TYPE,RECON_STATUS,OUT_OF_STATE_FLAG,CHARTER_TEXT,CHARTAUTH1,CHARTAUTHN1,CHARTAUTH2,CHARTAUTHN2,NOGRADES,G_PK_OFFERED,G_KG_OFFERED,G_1_OFFERED,G_2_OFFERED,G_3_OFFERED,G_4_OFFERED,G_5_OFFERED,G_6_OFFERED,G_7_OFFERED,G_8_OFFERED,G_9_OFFERED,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED,American Indian/Alaska Native (% total),Asian (% total),Black/African American (% total),Hispanic/Latino (% total),Hawaiian/Pacific Islander (% total),Not Specified (% total),Two+ races (% total),White (% total),Free or Reduced Lunch (% total),Total Student Count,TEACHERS,TOTAL_INDICATOR,DMS_FLAG,SHARED_TIME,TITLEI_STATUS,TITLEI_STATUS_TEXT,MAGNET_TEXT,NSLP_STATUS,NSLP_STATUS_TEXT,VIRTUAL,VIRTUAL_TEXT,NAME,OPSTFIPS,STREET,CITY,STATE,ZIP,STFIP,CNTY,NMCNTY,LOCALE,LAT,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,NECTA,NMNECTA,CD,SLDL,SLDU,SCHOOLYEAR
0,2017-2018,1,ALABAMA,AL,Acceleration Day and Evening Academy,Acceleration Day and Evening Academy,1,NaN,AL-800,100197,AL-800-0010,10019702432,102432,605 Bel Air Blvd Suite 400,NaN,NaN,Mobile,AL,36606,NaN,3100 Cottage Hill Rd,NaN,NaN,Mobile,AL,36606,NaN,(251)476-0002,http://www.maef.net,1,Open,1,Open,08/17/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,09,12,High,As reported,1.224490,0.816327,72.244898,1.632653,0.408163,0.0,3.265306,20.408163,80.816327,245.0,7.00,Education Unit Total,Reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Not reported,Acceleration Day and Evening Academy,1,3100 Cottage Hill Rd,Mobile,AL,36606,1,1097,Mobile County,12,30.668018,-88.119730,33660,"Mobile, AL",1,380,"Mobile-Daphne-Fairhope, AL",N,N,101,01103,01033,2017-2018
1,2017-2018,1,ALABAMA,AL,University Charter School,University Charter School,1,NaN,AL-801,100199,AL-801-0010,10019902452,102452,108 School Street,NaN,NaN,Livingston,AL,35470,NaN,108 School Street,NaN,NaN,Livingston,AL,35470,NaN,(205)652-3438,NaN,7,Future,7,Future,04/19/2018,Regular School,1,No,No,Yes,AL001,Alabama Public Charter School Commission,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,PK,08,Elementary,As reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,University Charter School,1,108 School Street,Livingston,AL,35470,1,1119,Sumter County,43,32.586288,-88.189067,N,N,0,N,N,N,N,107,01072,01024,2017-2018
2,2017-2018,2,ALASKA,AK,Ayaprun Elitnaurvik,Lower Kuskokwim School District,1,NaN,AK-31,200001,AK-31-319010,20000100329,200329,PO Box 1468,NaN,NaN,Bethel,AK,99559,1468.0,1010 Fourth Ave,NaN,NaN,Bethel,AK,99559,NaN,(907)543-1645,http://www.lksd.org/lksd/,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200001,Lower Kuskokwim School District,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,PK,06,Elementary,As reported,98.192771,0.602410,0.000000,0.000000,0.000000,0.0,0.000000,1.204819,69.277108,166.0,9.13,Education Unit Total,Reported,No,SWELIGTGPROG,Title I schoolwide eligible-Title I targeted a...,No,NSLPCEO,Yes under Community Eligibility Option (CEO),NOTVIRTUAL,Not Virtual,Ayaprun Elitnaurvik,2,1010 Fourth Ave,Bethel,AK,99559,2,2050,Bethel Census Area,33,60.796131,-161.765194,N,N,0,N,N,N,N,200,02038,0200S,2017-2018
3,2017-2018,2,ALASKA,AK,Ketchikan Charter School,Ketchikan Gateway Borough School District,1,NaN,AK-25,200150,AK-25-259010,20015000306,200306,410 Schoenbar Rd,NaN,NaN,Ketchikan,AK,99901,NaN,410 Schoenbar,NaN,NaN,Ketchikan,AK,99901,NaN,(907)225-8568,http://www.kgbsd.org/ketchikancharter,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200150,Ketchikan Gateway Borough School District,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,KG,08,Elementary,As reported,41.397849,13.978495,3.225806,5.913978,2.150538,0.0,5.376344,27.956989,53.225806,186.0,11.80,Education Unit Total,Reported,No,SWELIGTGPROG,Title I schoolwide eligible-Title I targeted a...,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Ketchikan Charter School,2,410 Schoenbar,Ketchikan,AK,99901,2,2130,Ketchikan Gateway Borough,33,55.347575,-131.640006,28540,"Ketchikan, AK",2,N,N,N,N,200,02036,0200R,2017-2018
4,2017-2018,2,ALASKA,AK,Tongass School of Arts and Sciences Charter Sc...,Ketchikan Gateway Borough School District,1,NaN,AK-25,200150,AK-25-259020,20015000523,200523,410 Schoenbar Rd Ste 202,NaN,NaN,Ketchikan,AK,99901,NaN,410 Schoenbar Rd,NaN,NaN,Ketchikan,AK,99901,NaN,(907)225-5720,http://www.tongassschool.org/,1,Open,1,Open,02/20/2018,Regular School,1,No,No,Yes,0200150,Ketchikan Gateway Borough School District,NaN,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,PK,06,Elementary,As reported,32.960894,5.586592,3.351955,0.558659,1.117318,0.0,11.173184,45.251397,50.837989,179.0,11.10,Education Unit Total,Reported,No,SWELIGTGPROG,Title I schoolwide eligible-Title I targeted a...,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Tongass School of Arts and Sciences Charter Sc...,2,410 Schoenbar Rd,Ketchikan,AK,99901,2,2130,Ketchikan Gateway Borough,33,55.347575,-131.640006,28540,"Ketchikan, AK",2,N,N,N,N,200,02036,0200R,2017-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7607,2017-2018,56,WYOMING,WY,Snowy Range Academy,Albany County School District #1,1,NaN,WY-0101000,5600730,WY-0101000-0101001,560073000216,5600216,4037 Grand Avenue,Suite A,NaN,Laramie,WY,82070,NaN,4037 Grand Avenue,NaN,NaN,Laramie,WY,82070,NaN,(307)745-9930,http://www.snowyrangeacademy.org/,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,KG,08,Elementary,As reported,0.000000,7.843137,1.470588,5.392157,0.000000,0.0,6.862745,78.431373,6.862745,204.0,20.50,Education Unit Total,Reported,No,NOTTITLE1ELIG,Not a Title I school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Snowy Range Academy,56,4037 Grand Avenue,Laramie,WY,82070,56,56001,Albany County,41,41.307523,-105.544698,29660,"Laramie, WY",2,N,N,N,N,5600,56014,56010,2017-2018
7608,2017-2018,56,WYOMING,WY,Laramie Montessori Charter School,Albany County School District #1,1,NaN,WY-0101000,5600730,WY-0101000-0101031,560073000542,5600542,608 S 4th St.,NaN,NaN,Laramie,WY,82070,NaN,608 S 4th St.,NaN,NaN,Laramie,WY,82070,NaN,(307)742-2554,http://www.laramiemontessori.org,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,KG,06,Elementary,As reported,3.750000,0.000000,0.000000,18.750000,0.000000,0.0,5.000000,72.500000,46.250000,80.0,7.41,Education Unit Total,Reported,No,TGELGBTGPROG,Title I targeted assistance school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Laramie Montessori Charter School,56,608 S 4th St.,Laramie,WY,82070,56,56001,Albany County,33,41.307729,-105.593028,29660,"Laramie, WY",2,N,N,N,N,5600,56045,56009,2017-2018
7609,2017-2018,56,WYOMING,WY,Arapahoe Charter High School,Fremont County School District #38,1,NaN,WY-0738000,5600960,WY-0738000-0738055,560096000367,5600367,445 Little Wind River Bottom R,NaN,NaN,Arapahoe,WY,82510,NaN,445 Little Wind River Bottom R,NaN,NaN,Arapahoe,WY,82510,NaN,(307)856-3862,http://www.fcsd38.org,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,09,12,High,As reported,100.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,91.666667,36.0,3.14,Education Unit Total,Reported,No,SWELIGSWPROG,Title I schoolwide school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,Arapahoe Charter High School,56,445 Little Wind River Bottom R,Arapahoe,WY,82510,56,56013,Fremont County,42,42.963943,-108.490183,40180,"Riverton, WY",2,N,N,N,N,5600,56033,56025,2017-2018
7610,2017-2018,56,WYOMING,WY,PODER Academy,Laramie County School District #1,1,NaN,WY-1101000,5601980,WY-1101000-1101040,560198000547,5600547,2201 Morrie Ave,NaN,NaN,Cheyenne,WY,82001,NaN,2201 Morrie Ave,NaN,NaN,Cheyenne,WY,82001,NaN,(307)632-2248,http://poderacademy.com,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,No,No,No,KG,05,Elementary,As reported,0.574713,0.574713,1.149425,29.310345,1.149425,0.0,6.321839,60.919540,47.126437,174.0,8.25,Education Unit Total,Reported,No,SWELIGSWPROG,Title I schoolwide school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,PODER Academy,56,2201 Morrie Ave,Cheyenne,WY,82001,56,56021,Laramie County,13,41.142854,-104.807608,16940,"Cheyenne, WY",1,N,N,N,N,5600,56011,56007,2017-2018
7611,2017-2018,56,WYOMING,WY,PODER Academy Secondary School,Laramie County School District #1,1,NaN,WY-1101000,5601980,WY-1101000-1101045,560198000574,5600574,2201 Morrie Avenue,NaN,NaN,Cheyenne,WY,82001,NaN,2201 Morrie Avenue,NaN,NaN,Cheyenne,WY,82001,NaN,(307)632-2248,http://www.poderacademy.com,1,Open,1,Open,05/10/2018,Regular School,1,No,No,Yes,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,No,No,No,06,09,Middle,As reported,2.666667,0.000000,5.333333,32.000000,1.333333,0.0,2.666667,56.000000,58.666667,75.0,2.70,Education Unit Total,Reported,No,TGELGBTGPROG,Title I targeted assistance school,No,NSLPWOPRO,Yes participating without using any Provision ...,NOTVIRTUAL,Not Virtual,PODER Academy Secondary School,56,2201 Morrie Avenue,Cheyenne,WY,82001,56,56021,Laramie County,13,41.142854,-104.807608,16940,"Cheyenne, WY",1,N,N,N,N,5600,56011,56007,2017-2018

In [71]:
# Save final, cleaned data set
cleaned_charter.to_csv(data_fp + "ccd_201718/ccd_charters_merged_1718.csv", header = True)
cleaned_charter.to_excel(data_fp + "ccd_201718/ccd_charters_merged_1718.xlsx", header = True)